[package]
name = "src"
version = "0.1.0"
cairo-version = "2.6.3"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.21.0" }
chainlink = { path = "../../../../contracts" }
aggregator_consumer = { path = "../" }
starknet = ">=2.6.3"

[lib]
casm = true

[[target.starknet-contract]]
casm = true
build-external-contracts = [
  "chainlink::emergency::sequencer_uptime_feed::SequencerUptimeFeed",
  "chainlink::ocr2::mocks::mock_aggregator::MockAggregator",
  "aggregator_consumer::ocr2::consumer::AggregatorConsumer"
]

