name: E2E Custom image build tests
on:
  pull_request:
  workflow_dispatch:
    inputs:
      cl_branch_ref:
        description: Chainlink repo branch to integrate with
        required: true
        default: develop
        type: string

# Only run 1 of this workflow at a time per PR
concurrency:
  group: integration-tests-starknet-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e_custom_build_custom_chainlink_image:
    name: E2E Custom Build Custom CL Image
    runs-on: ubuntu-latest
    environment: integration
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Build Image
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/build-image@1f3c81b148e53caaa0563f8963f884f0e5a4f82d # v2.0.15
        with:
          cl_repo: smartcontractkit/chainlink
          # By default we are integrating with CL develop
          # cl_ref: ${{ github.event.inputs.cl_branch_ref }}
          cl_ref: 22c6ac0237a85010b91154277533dfd6acc8912c # https://github.com/smartcontractkit/chainlink/pull/7366
          # commit of the caller branch
          dep_starknet_sha: ${{ github.event.pull_request.head.sha || github.sha }}
          push_tag: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink:custom.${{ github.sha }}
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          QA_PRIVATE_GHA_PULL: ${{ secrets.QA_PRIVATE_GHA_PULL }}
  e2e_custom_run_smoke_tests:
    name: E2E Custom Run Smoke Tests
    runs-on: ubuntu-latest
    needs: [ e2e_custom_build_custom_chainlink_image ]
    environment: integration
    env:
      CGO_ENABLED: 1
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.0.2
      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Install Nix
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590 # v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run Tests
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/run-tests@1f3c81b148e53caaa0563f8963f884f0e5a4f82d # v2.0.15
        with:
          test_command_to_run: nix develop -c make test-integration-smoke
          test_download_vendor_packages_command: cd integration-tests && go mod download
          cl_repo: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
          cl_image_tag: custom.${{ github.sha }}
          publish_report_paths: "./tests-smoke-report.xml"
          publish_check_name: Smoke Test Results
          artifacts_location: /home/runner/work/chainlink-starknet/chainlink-starknet/tests/e2e/logs
          token: ${{ secrets.GITHUB_TOKEN }}
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}

  e2e_custom_run_soak_tests:
    name: E2E Custom Run Soak Tests
    runs-on: ubuntu-latest
    needs: [ e2e_custom_build_custom_chainlink_image ]
    environment: integration
    env:
      CGO_ENABLED: 1
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3.0.2
      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Install Nix
        uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590 # v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run Tests
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/run-tests@1f3c81b148e53caaa0563f8963f884f0e5a4f82d # v2.0.15
        with:
          test_command_to_run: nix develop -c make test-integration-soak
          test_download_vendor_packages_command: cd integration-tests && go mod download
          cl_repo: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
          cl_image_tag: custom.${{ github.sha }}
          publish_report_paths: "./tests-soak-report.xml"
          publish_check_name: Smoke Test Results
          artifacts_location: /home/runner/work/chainlink-starknet/chainlink-starknet/tests/e2e/logs
          token: ${{ secrets.GITHUB_TOKEN }}
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}