name: E2E Custom image build tests
on:
  push:
  workflow_dispatch:
    inputs:
      cl_branch_ref:
        description: Chainlink repo branch to integrate with
        required: true
        default: starknet-bump
        type: string

jobs:
  e2e_custom_build_custom_chainlink_image:
    name: E2E Custom Build Custom CL Image
    runs-on: ubuntu-latest
    environment: integration
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Build Image
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/build-image@7d405e28e1419c0a48198793e6647005c409f4cf # v2.0.4
        with:
          cl_repo: smartcontractkit/chainlink
          # by default we are integrating with develop
          cl_ref: ${{ github.event.inputs.cl_branch_ref }}
          # commit of the caller branch
          dep_starknet_sha: ${{ github.sha }}
          push_tag: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink:custom.${{ github.sha }}
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          QA_PRIVATE_GHA_PULL: ${{ secrets.QA_PRIVATE_GHA_PULL }}
          GOPRIVATE: github.com/smartcontractkit/chainlink-starknet/relayer
  e2e_cutsom_run_smoke_tests:
    name: E2E Custom Run Smoke Tests
    runs-on: ubuntu-latest
    needs: [ e2e_custom_build_custom_chainlink_image ]
    environment: integration
    env:
      CGO_ENABLED: 1
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@f25a3a9f25bd5f4c5d77189cab02ff357b5aedeb # v2.4.1
      - name: Run Tests
        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/run-tests@7d405e28e1419c0a48198793e6647005c409f4cf # v2.0.4
        with:
          test_command_to_run: make e2e_test
          test_download_vendor_packages_command: cd integration-tests && go mod download
          cl_repo: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
          cl_image_tag: custom.${{ github.sha }}
          publish_report_paths: "./tests-smoke-report.xml"
          publish_check_name: Smoke Test Results
          artifacts_location: /home/runner/work/chainlink-starknet/chainlink-starknet/tests/e2e/logs
          token: ${{ secrets.GITHUB_TOKEN }}
          QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
          QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}